class_name Sfx
extends RefCounted
## Sound effects: positional one-shots (gunshots, explosions, footsteps) and UI blips
## (hit marker, kill). Cosmetic only, played locally on each peer. Recorded clips from the
## "FREE FPS SFX Pack" (footsteps, shotgun, sniper, rocket, explosion, scope, grapple, warning;
## converted to mono by tools/convert_sfx_pack.sh), knife swish and draw scrape (Freesound,
## see docs/ASSETS.md); the rest (rifle, light, rail, hit, kill) are generated by tools/gen_sfx.py.

const SHOT_LIGHT: AudioStream = preload("res://assets/audio/shot_light.wav")
const SHOT_RIFLE: AudioStream = preload("res://assets/audio/shot_rifle.wav")
const SHOT_HEAVY: Array[AudioStream] = [
	preload("res://assets/audio/shot_heavy_1.wav"), preload("res://assets/audio/shot_heavy_2.wav"),
	preload("res://assets/audio/shot_heavy_3.wav"), preload("res://assets/audio/shot_heavy_4.wav"),
]
const SHOT_SHOTGUN: Array[AudioStream] = [
	preload("res://assets/audio/shot_shotgun_1.wav"), preload("res://assets/audio/shot_shotgun_2.wav"),
	preload("res://assets/audio/shot_shotgun_3.wav"), preload("res://assets/audio/shot_shotgun_4.wav"),
]
const SHOT_RAIL: AudioStream = preload("res://assets/audio/shot_rail.wav")
const SHOT_SUPPRESSED: AudioStream = preload("res://assets/audio/shot_suppressed.wav")
const SONAR: AudioStream = preload("res://assets/audio/sonar.wav")
const DART: AudioStream = preload("res://assets/audio/dart.wav")
const TELEPORT: AudioStream = preload("res://assets/audio/teleport.wav")
const CLOAK: AudioStream = preload("res://assets/audio/cloak.wav")
const DICE: AudioStream = preload("res://assets/audio/dice.wav")
const DICE_GOOD: AudioStream = preload("res://assets/audio/dice_good.wav")
const DICE_BAD: AudioStream = preload("res://assets/audio/dice_bad.wav")
const SHOT_LAUNCHER: Array[AudioStream] = [
	preload("res://assets/audio/shot_launcher_1.wav"), preload("res://assets/audio/shot_launcher_2.wav"),
	preload("res://assets/audio/shot_launcher_3.wav"), preload("res://assets/audio/shot_launcher_4.wav"),
]
const EXPLOSION: Array[AudioStream] = [
	preload("res://assets/audio/explosion_1.wav"), preload("res://assets/audio/explosion_2.wav"),
	preload("res://assets/audio/explosion_3.wav"), preload("res://assets/audio/explosion_4.wav"),
]
const SHOTGUN_PUMP: AudioStream = preload("res://assets/audio/shotgun_pump.wav")
const SCOPE_IN: AudioStream = preload("res://assets/audio/scope_in.wav")
const GRAPPLE_SHOT: AudioStream = preload("res://assets/audio/grapple_shot.wav")
const GRAPPLE_HOOK: AudioStream = preload("res://assets/audio/grapple_hook.wav")
const WARNING: AudioStream = preload("res://assets/audio/warning.wav")
const KNIFE_DRAW: AudioStream = preload("res://assets/audio/knife_draw.wav")
const LAND: AudioStream = preload("res://assets/audio/land.wav")
const HIT: AudioStream = preload("res://assets/audio/hit.wav")
const HIT_HEAD: AudioStream = preload("res://assets/audio/hit_head.wav")
const KILL: AudioStream = preload("res://assets/audio/kill.wav")
const SWING: AudioStream = preload("res://assets/audio/swing.wav")
const STEPS: Array[AudioStream] = [
	preload("res://assets/audio/step_1.wav"), preload("res://assets/audio/step_2.wav"),
	preload("res://assets/audio/step_3.wav"), preload("res://assets/audio/step_4.wav"),
	preload("res://assets/audio/step_5.wav"), preload("res://assets/audio/step_6.wav"),
	preload("res://assets/audio/step_7.wav"), preload("res://assets/audio/step_8.wav"),
]

const SHOT_DB: float = -4.0
const EXPLOSION_DB: float = 2.0
const STEP_DB: float = -8.0
const LAND_DB: float = -5.0
const SUPPRESSED_DB: float = -10.0
const SUPPRESSED_MAX_DISTANCE: float = 12.0 ## A silenced shot is not heard further away.
## Footsteps carry like CS (heard through a wall or two, ~30 m), panned hard to their side.
const STEP_UNIT_SIZE: float = 5.0
const STEP_MAX_DISTANCE: float = 32.0
const UI_DB: float = -8.0
const LEG_HIT_PITCH: float = 0.7 ## A leg hit is the body tick, lower and duller.
const PITCH_JITTER: float = 0.06
const UNIT_SIZE: float = 8.0 ## Metres at which a sound is at its full volume.
const MAX_DISTANCE: float = 120.0


## Plays `stream` once at `point` in `parent`'s world; the player frees itself afterwards.
static func play_at(parent: Node, stream: AudioStream, point: Vector3, volume_db: float = 0.0, unit_size: float = UNIT_SIZE, max_distance: float = MAX_DISTANCE) -> void:
	if parent == null or not parent.is_inside_tree() or DisplayServer.get_name() == "headless":
		return
	var audio := AudioStreamPlayer3D.new()
	audio.stream = stream
	audio.volume_db = volume_db + _master_db()
	audio.unit_size = unit_size
	audio.max_distance = max_distance
	audio.panning_strength = 1.0 # Full left/right: you hear which side it came from.
	audio.doppler_tracking = AudioStreamPlayer3D.DOPPLER_TRACKING_DISABLED
	audio.pitch_scale = randf_range(1.0 - PITCH_JITTER, 1.0 + PITCH_JITTER)
	audio.attenuation_filter_cutoff_hz = 8000.0
	audio.finished.connect(audio.queue_free)
	parent.add_child(audio)
	audio.global_position = point
	audio.play()


## Non-positional (hit marker, kill confirm).
static func play_ui(parent: Node, stream: AudioStream, volume_db: float = UI_DB, pitch: float = 1.0) -> void:
	if parent == null or not parent.is_inside_tree() or DisplayServer.get_name() == "headless":
		return
	var audio := AudioStreamPlayer.new()
	audio.stream = stream
	audio.volume_db = volume_db + _master_db()
	audio.pitch_scale = pitch
	audio.finished.connect(audio.queue_free)
	parent.add_child(audio)
	audio.play()


## Hit marker sound for a hit the shooter sees confirmed: body tick, duller leg tick, bright
## head ding; a kill plays the kill chime (with the head ding on top for a headshot kill).
static func hit_confirm(parent: Node, zone: Hitbox.Zone, killed: bool) -> void:
	if killed:
		play_ui(parent, KILL)
		if zone == Hitbox.Zone.HEAD:
			play_ui(parent, HIT_HEAD)
		return
	match zone:
		Hitbox.Zone.HEAD:
			play_ui(parent, HIT_HEAD)
		Hitbox.Zone.LEG:
			play_ui(parent, HIT, UI_DB, LEG_HIT_PITCH)
		_:
			play_ui(parent, HIT)


static func shot(parent: Node, def: WeaponDef, point: Vector3) -> void:
	if def == null:
		return
	if def.suppressed:
		play_at(parent, SHOT_SUPPRESSED, point, SUPPRESSED_DB, STEP_UNIT_SIZE * 0.6, SUPPRESSED_MAX_DISTANCE)
		return
	play_at(parent, shot_stream(def), point, SHOT_DB, UNIT_SIZE * 2.0)


## Picks the gunshot clip from the weapon's stats, so new weapons get a fitting sound.
static func shot_stream(def: WeaponDef) -> AudioStream:
	if not def.fire_sounds.is_empty():
		return def.fire_sounds.pick_random()
	if def.grenade != null:
		return SHOT_LAUNCHER.pick_random()
	if def.pierce_walls:
		return SHOT_RAIL
	if not def.pellet_pattern.is_empty():
		return SHOT_SHOTGUN.pick_random()
	if def.damage >= 45.0:
		return SHOT_HEAVY.pick_random()
	if def.damage >= 20.0 or def.fire_interval >= 0.25:
		return SHOT_RIFLE
	return SHOT_LIGHT


static func explosion(parent: Node, point: Vector3) -> void:
	play_at(parent, EXPLOSION.pick_random(), point, EXPLOSION_DB, UNIT_SIZE * 3.0)


static func step(parent: Node, point: Vector3) -> void:
	play_at(parent, STEPS.pick_random(), point, STEP_DB, STEP_UNIT_SIZE, STEP_MAX_DISTANCE)


## Landing from a jump or fall: both feet, a little louder than a step (no boom).
static func land(parent: Node, point: Vector3) -> void:
	play_at(parent, LAND, point, LAND_DB, STEP_UNIT_SIZE, STEP_MAX_DISTANCE)


## A reload starting (owner and, through SoldierRig actions, everyone else): pump-action guns
## rack the pump; other guns are silent for now.
static func reload(parent: Node, def: WeaponDef, point: Vector3) -> void:
	if def != null and not def.pellet_pattern.is_empty():
		play_at(parent, SHOTGUN_PUMP, point, STEP_DB + 2.0, STEP_UNIT_SIZE, STEP_MAX_DISTANCE)


static func _master_db() -> float:
	return linear_to_db(maxf(Settings.sfx_volume, 0.0001))
